version: "3.5"

services:

    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - frontend

    mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod 
        environment:
            MONGO_INITDB_DATABASE: thesis-manager
            MONGODB_DATA_DIR: /data/db
        volumes:
            - mongodbdata:/data/db
            - ./backend/mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js
        networks:
            - backend

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        environment:
            MONGODB_HOST: mongodb
        volumes:
            - appdata:/var/www/
        depends_on: 
            - mongodb
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge


volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local